In [1]:
import pandas as pd
import numpy as np

expected_returns = pd.read_csv("../data/results/expected_returns.csv", index_col=0).iloc[:, 0]
betas = pd.read_csv("../data/processed/factor_betas.csv", index_col=0)
merged = pd.read_csv("../data/processed/merged_dataset.csv", index_col=0, parse_dates=True)

In [2]:
top_stocks = expected_returns.head(20)
top_stocks

NVDA      0.364163
AVGO      0.296053
AAPL      0.290227
META      0.265266
MSFT      0.264660
ADBE      0.253379
GOOGL     0.238380
MA        0.235503
BA        0.234817
TSLA      0.227287
HD        0.220511
BLK       0.217028
AXP       0.214303
SBUX      0.210057
AMZN      0.208973
NKE       0.208093
V         0.205499
MS        0.203356
GE        0.202399
Mkt-RF    0.194496
Name: 0, dtype: float64

In [3]:
n = len(top_stocks)
weights_equal = np.ones(n) / n
weights_equal

array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
       0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])

In [4]:
portfolio_return_equal = np.dot(weights_equal, top_stocks.values)
portfolio_return_equal

np.float64(0.2377225940237095)

In [5]:
factor_cols = ["Market", "SMB", "HML", "RMW", "CMA"]

beta_subset = betas.loc[top_stocks.index, factor_cols]

portfolio_exposure_equal = np.dot(weights_equal, beta_subset)
portfolio_exposure_equal

array([ 1.18063876, -0.03752703, -0.02837528,  0.08659746, -0.24116978])

In [6]:
bottom_stocks = expected_returns.tail(10)
bottom_stocks


SLB     0.153609
CVX     0.151651
PG      0.149402
KO      0.148258
EOG     0.136253
ABBV    0.126451
PFE     0.122001
XOM     0.121861
JNJ     0.121306
MRK     0.117205
Name: 0, dtype: float64

In [7]:
long_names = top_stocks.head(10).index
short_names = bottom_stocks.index

weights_longshort = pd.Series(0, index=expected_returns.index)

# long positions: +0.05 each
weights_longshort[long_names] = 0.1

# short positions: -0.05 each
weights_longshort[short_names] = -0.1

weights_longshort = weights_longshort[weights_longshort != 0]
weights_longshort

C:\Users\mshri\AppData\Local\Temp\ipykernel_13668\2321976068.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  weights_longshort[long_names] = 0.1


NVDA     0.1
AVGO     0.1
AAPL     0.1
META     0.1
MSFT     0.1
ADBE     0.1
GOOGL    0.1
MA       0.1
BA       0.1
TSLA     0.1
SLB     -0.1
CVX     -0.1
PG      -0.1
KO      -0.1
EOG     -0.1
ABBV    -0.1
PFE     -0.1
XOM     -0.1
JNJ     -0.1
MRK     -0.1
dtype: float64

In [8]:
ls_return = np.dot(weights_longshort, expected_returns.loc[weights_longshort.index])
ls_return

np.float64(0.1321737836696589)

In [9]:
beta_ls = betas.loc[weights_longshort.index, factor_cols]
portfolio_exposure_ls = np.dot(weights_longshort, beta_ls)
portfolio_exposure_ls

array([ 0.5027619 ,  0.10152852, -0.76346735,  0.28226583, -0.72361791])